version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres-host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

  multi-db-aggregator:
    build: ./multi-db-aggregator
    ports:
      - "7878:7878"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge